// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// This code gave error of older way to use the prisma::
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

// prisma.config.ts with revized coding logic
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./prisma",
  datasource: {
    url: process.env.DATABASE_URL, // using typescript format should be same.
  },
});
